#!/usr/bin/env bash
set -euo pipefail

echo "1) Ensure IPPAN DevNet is running and IPPAN_RPC_URL is reachable."
echo "2) Export:"
echo "   export ETH_RPC_URL=..."
echo "   export ETH_PRIVATE_KEY=..."
echo "   export IPPAN_RPC_URL=http://<devnet-node>:8080"
echo "   export UPDATER_ADDRESS=<EOA derived from ETH_PRIVATE_KEY>"
echo ""
echo "3) cd integrations/eth-oracle/contracts"
echo "   forge test"
echo "   forge build"
echo "   forge script script/DeployIppanAiOracle.s.sol --rpc-url \\$ETH_RPC_URL --private-key \\$ETH_PRIVATE_KEY --broadcast"
echo ""
echo "4) Note the deployed IppanAiOracle address and update:"
echo "   integrations/eth-oracle/configs/devnet_sepolia.toml -> ethereum.oracle_contract_address"
echo ""
echo "5) From repo root, run:"
echo "   ETH_PRIVATE_KEY=\\$ETH_PRIVATE_KEY ETH_RPC_URL=\\$ETH_RPC_URL IPPAN_RPC_URL=\\$IPPAN_RPC_URL \\"
echo "   cargo run -p ippan_eth_oracle_daemon -- watch --config integrations/eth-oracle/configs/devnet_sepolia.toml"
echo ""
echo "6) Use cast to verify scores on-chain. Example:"
echo "   cast call <oracle_address> \"getScore(bytes32)\" 0x<subject_id_hex>"
echo ""
echo "7) Example on-chain query (label + score):"
echo "   cast call <oracle_address> \"getSubject(bytes32)\" 0x<subject_id_hex>"
